"""
api/main.py
───────────
FastAPI application that serves the trained Heart Disease Risk prediction model.

Endpoints:
  POST /predict         — single patient prediction
  POST /predict-batch   — batch predictions (up to 100 patients)
  GET  /model-info      — model type, feature list, dataset info
  GET  /stats           — live prediction counts since startup
  GET  /health          — liveness check (is the API running?)
  GET  /ready           — readiness check (is the model loaded?)
  GET  /metrics         — Prometheus metrics (auto-exposed)
  GET  /docs            — Swagger UI (auto-generated by FastAPI)

Design decisions:
  - engineer_features() is called at inference time, same as at training time,
    to ensure the 5 derived features are always computed consistently
  - CATEGORICAL_FEATURES are cast to float before prediction because the
    OneHotEncoder was fitted on float values from the CSV — int inputs cause
    an "unknown categories" error
  - All predictions are logged in structured format for audit and monitoring
  - Prometheus metrics track both technical (latency, request count) and
    business-level (high vs low risk count) signals
"""
import logging
import sys
import time
from pathlib import Path
from typing import List

import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException
from prometheus_fastapi_instrumentator import Instrumentator
from prometheus_client import Counter, Histogram
from pydantic import BaseModel, Field

# Add src/ to Python path so we can import preprocess.py
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from preprocess import CATEGORICAL_FEATURES, engineer_features  # noqa: E402

# ── Logging setup ─────────────────────────────────────────────────────────────
# Structured log format: timestamp + level + message
# Every prediction call logs age, sex, cp, probability, risk, and heart_rate_reserve
# This creates an audit trail usable for drift monitoring
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
)
logger = logging.getLogger(__name__)

# ── FastAPI app ───────────────────────────────────────────────────────────────
# openapi_tags groups endpoints in the Swagger UI into logical sections
app = FastAPI(
    title="Heart Disease Risk API",
    description=(
        "Predicts heart disease risk from patient health data. "
        "Uses a Random Forest classifier trained on the UCI Heart Disease (Cleveland) dataset. "
        "Features include clinical measurements and derived biomarkers (heart rate reserve, "
        "BP category per JNC-8, cholesterol risk tier per ATP III)."
    ),
    version="1.0.0",
    docs_url="/docs",    # Swagger UI URL
    redoc_url="/redoc",  # ReDoc UI URL (alternative documentation)
    openapi_tags=[
        {"name": "health",  "description": "Liveness and readiness checks"},
        {"name": "predict", "description": "Model inference endpoints"},
        {"name": "model",   "description": "Model metadata and runtime stats"},
    ],
)

# ── Prometheus metrics ────────────────────────────────────────────────────────
# Instrumentator auto-instruments all HTTP endpoints with:
#   - http_requests_total (counter by endpoint, method, status)
#   - http_request_duration_seconds (histogram per endpoint)
# .expose(app) adds the /metrics endpoint that Prometheus scrapes
Instrumentator().instrument(app).expose(app)

# Custom business-level metrics specific to this application
prediction_counter = Counter(
    "heart_risk_predictions_total",       # metric name
    "Total predictions by risk level",    # description
    ["risk_level"],                        # label: "high" or "low"
    # Use case: alert if high_risk rate spikes unexpectedly (possible data drift)
)

prediction_latency = Histogram(
    "heart_risk_prediction_duration_seconds",
    "Time taken per prediction",
    # Use case: detect model loading issues or compute bottlenecks
)

batch_size_histogram = Histogram(
    "heart_risk_batch_size",
    "Batch prediction sizes",
    buckets=[1, 5, 10, 25, 50, 100],  # predefined bucket boundaries for the histogram
)

# ── Model loading ─────────────────────────────────────────────────────────────
# Load the fitted pipeline at startup (not per-request) for performance.
# The pipeline object contains both the preprocessor and the classifier —
# a single pipeline.predict(X) call applies all transformations and returns predictions.
MODEL_PATH = Path(__file__).parent.parent / "models" / "pipeline.pkl"
pipeline = joblib.load(MODEL_PATH)

# In-memory counters for the /stats endpoint
# These reset when the API restarts (not persisted to disk)
_stats = {"total_predictions": 0, "high_risk": 0, "low_risk": 0}

# The 13 raw UCI features that the API accepts from the client
RAW_FEATURES = [
    "age", "sex", "cp", "trestbps", "chol", "fbs",
    "restecg", "thalach", "exang", "oldpeak", "slope", "ca", "thal"
]


# ── Request / Response schemas ────────────────────────────────────────────────

class PatientData(BaseModel):
    """Input schema — the 13 raw clinical measurements from the UCI dataset."""

    # model_config provides the example shown in Swagger UI
    model_config = {"json_schema_extra": {"example": {
        "age": 55, "sex": 1, "cp": 1, "trestbps": 130, "chol": 250,
        "fbs": 0, "restecg": 0, "thalach": 150, "exang": 0,
        "oldpeak": 1.5, "slope": 1, "ca": 0, "thal": 3
    }}}

    age: float = Field(..., description="Age in years")
    sex: int   = Field(..., description="1=male, 0=female")
    cp: int    = Field(..., description="Chest pain: 1=typical, 2=atypical, 3=non-anginal, 4=asymptomatic")  # noqa: E501
    trestbps: float = Field(..., description="Resting blood pressure (mmHg)")
    chol: float     = Field(..., description="Serum cholesterol (mg/dl)")
    fbs: int        = Field(..., description="Fasting blood sugar > 120 mg/dl (1=true)")
    restecg: int    = Field(..., description="Resting ECG: 0=normal, 1=ST-T wave, 2=LV hypertrophy")
    thalach: float  = Field(..., description="Max heart rate achieved")
    exang: int      = Field(..., description="Exercise induced angina (1=yes)")
    oldpeak: float  = Field(..., description="ST depression induced by exercise")
    slope: int      = Field(..., description="Slope of peak ST: 1=upsloping, 2=flat, 3=downsloping")
    ca: float   = Field(..., description="Number of major vessels coloured by fluoroscopy (0-3)")
    thal: float = Field(..., description="Thal: 3=normal, 6=fixed defect, 7=reversable defect")


class PredictionResponse(BaseModel):
    """Output schema — prediction + clinical context."""
    prediction:         int    # 0 = no disease, 1 = disease present
    probability:        float  # confidence score (0.0 to 1.0)
    risk:               str    # "low" or "high" (human-readable label)
    heart_rate_reserve: float  # derived clinical feature: (220 - age) - thalach
    age_thalach_ratio:  float  # derived: thalach / age (fitness relative to age)


class BatchPredictionResponse(BaseModel):
    """Output schema for batch predictions."""
    results:         List[PredictionResponse]
    count:           int  # total patients in the batch
    high_risk_count: int  # number predicted as high risk
    low_risk_count:  int  # number predicted as low risk


# ── Core prediction logic ─────────────────────────────────────────────────────

def _make_prediction(data: PatientData) -> PredictionResponse:
    """
    Run the full inference pipeline for a single patient.

    Steps:
      1. Convert Pydantic model to DataFrame
      2. Apply engineer_features() — same function used during training
      3. Cast categorical columns to float (OHE was fitted on float values)
      4. Run pipeline.predict() and pipeline.predict_proba()
      5. Update Prometheus metrics and in-memory stats
      6. Log structured request entry
      7. Return structured response
    """
    # Step 1: Convert input to a single-row DataFrame
    df = pd.DataFrame([data.model_dump()])

    # Step 2: Add the 5 derived clinical features
    # (heart_rate_reserve, age_thalach_ratio, st_slope_interaction, bp_category, chol_risk)
    df = engineer_features(df)

    # Step 3: Cast categorical columns to float
    # The OneHotEncoder was fitted on float values from the CSV.
    # If integers are passed (e.g. cp=1 as int vs 1.0 as float), the encoder
    # raises "Found unknown categories" — casting prevents this.
    for col in CATEGORICAL_FEATURES:
        df[col] = df[col].astype(float)

    # Step 4: Run model inference and time it
    start = time.time()
    prediction  = int(pipeline.predict(df)[0])              # hard label: 0 or 1
    probability = float(pipeline.predict_proba(df)[0][1])   # probability of class 1
    prediction_latency.observe(time.time() - start)         # record latency in histogram

    risk = "high" if prediction == 1 else "low"

    # Step 5: Update Prometheus counters and in-memory stats
    prediction_counter.labels(risk_level=risk).inc()
    _stats["total_predictions"] += 1
    _stats[f"{risk}_risk"] += 1

    # Step 6: Structured log — one line per prediction for audit trail
    logger.info(
        "PREDICT age=%.0f sex=%d cp=%d prob=%.4f result=%s hr_reserve=%.1f",
        data.age, data.sex, data.cp, probability, risk,
        float(df["heart_rate_reserve"].iloc[0]),
    )

    # Step 7: Return structured response including derived clinical values
    return PredictionResponse(
        prediction         = prediction,
        probability        = round(probability, 4),
        risk               = risk,
        heart_rate_reserve = round(float(df["heart_rate_reserve"].iloc[0]), 2),
        age_thalach_ratio  = round(float(df["age_thalach_ratio"].iloc[0]), 4),
    )


# ── API endpoints ─────────────────────────────────────────────────────────────

@app.get("/health", tags=["health"])
def health():
    """Liveness probe — confirms the API process is running."""
    return {"status": "ok", "model": "heart-disease-classifier", "version": "1.0.0"}


@app.get("/ready", tags=["health"])
def ready():
    """
    Readiness probe — confirms the model is loaded and ready to serve.
    Kubernetes uses this to decide whether to route traffic to a pod.
    If the model file is missing or corrupted, pipeline will be None.
    """
    if pipeline is None:
        return {"ready": False, "reason": "model not loaded"}
    return {"ready": True}


@app.get("/model-info", tags=["model"])
def model_info():
    """Return metadata about the loaded model."""
    clf = pipeline.named_steps["classifier"]
    return {
        "model_type":         type(clf).__name__,  # e.g. "RandomForestClassifier"
        "n_features_in":      int(pipeline.named_steps["preprocessor"].n_features_in_),
        "engineered_features": [
            "heart_rate_reserve", "age_thalach_ratio",
            "st_slope_interaction", "bp_category", "chol_risk"
        ],
        "training_dataset": "UCI Heart Disease — Cleveland (297 samples)",
        "target": "Binary: 0=No Disease, 1=Disease Present",
    }


@app.get("/stats", tags=["model"])
def stats():
    """Return prediction counts since the API started (resets on restart)."""
    total = _stats["total_predictions"]
    high  = _stats["high_risk"]
    low   = _stats["low_risk"]
    return {
        "total_predictions": total,
        "high_risk":         high,
        "low_risk":          low,
        # high_risk_rate: useful for detecting sudden distribution shifts
        "high_risk_rate": round(high / total, 4) if total > 0 else 0.0,
    }


@app.post("/predict", response_model=PredictionResponse, tags=["predict"])
def predict(data: PatientData):
    """
    Predict heart disease risk for a single patient.

    Returns prediction (0/1), probability score, risk label ("low"/"high"),
    and two derived clinical features (heart rate reserve, age-normalised HR).
    """
    return _make_prediction(data)


@app.post("/predict-batch", response_model=BatchPredictionResponse, tags=["predict"])
def predict_batch(patients: List[PatientData]):
    """
    Predict heart disease risk for a batch of patients (up to 100).

    Returns individual predictions for each patient plus aggregate counts
    (total high-risk, total low-risk) for quick batch-level assessment.
    """
    # Validate batch size before processing
    if len(patients) == 0:
        raise HTTPException(status_code=400, detail="Batch must contain at least one patient.")
    if len(patients) > 100:
        raise HTTPException(status_code=400, detail="Batch size cannot exceed 100 patients.")

    # Record batch size for monitoring
    batch_size_histogram.observe(len(patients))

    # Run prediction for each patient in the batch
    results = [_make_prediction(p) for p in patients]
    high = sum(1 for r in results if r.risk == "high")

    return BatchPredictionResponse(
        results        = results,
        count          = len(results),
        high_risk_count= high,
        low_risk_count = len(results) - high,
    )
